version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    command: ["python", "-m", "backend.main"]
    working_dir: /app/backend

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    command: ["celery", "-A", "worker.tasks", "worker", "--loglevel=info", "--pool=solo"]
    working_dir: /app/backend

volumes:
  redis_data: 